### ISSUE TITLE
到第三步，后面不知道怎么填写

### ISSUE THREAD

**Issue by XiaoPangW** [JakLiao/GoodGoodName#4]
综合计算的结果： 2 [(3, 15, '土金金', '大吉'), (11, 7, '土土金', '大吉')]

那填入 self_wuxing_dict 文件中是否是

3 土 3金
15 土 15金

11 土 11金
7 土 7 金 

其他的水 木 火  不填写值？

**Comment by JakLiao** [comment]
不是的。第3步骤只是看需要的笔画，按照第4步说的，只要是喜欢的字都可以填上的。 但是如果配置文件中的喜用神字段有填写，那范围会进一步缩小。

**Comment by JakLiao** [comment]
有界面版本正在开发中，预计下半年才出。

**Comment by XiaoPangW** [comment]
谢谢
