### ISSUE TITLE
有些汉字会编码报错

### ISSUE THREAD

**Issue by xxzj990** [JakLiao/GoodGoodName#5]
如下图：

![微信截图_20190420162744](https://user-images.githubusercontent.com/5134154/56454838-62287a00-6389-11e9-8aa6-6b54849fc7f3.png)

**Comment by JakLiao** [comment]
这是因为测分数的网站不支持罕见字，目前我也没好点的办法。如果喜欢的话，去其他网站试试。
我建议是不要用生僻字，登记孩子姓名有可能会不通过的。

**Comment by xxzj990** [comment]
谢谢
